### ISSUE TITLE
Restart on Crash

### ISSUE THREAD

**Issue by DarkBlade177** [TCPR/ThermosServer#2]
Sorry, i am new to linux and i want to know a script to restart the server when it crash, or when i use the command `/restart` can you help me ? :D

**Comment by thomas15v** [comment]
Linux: 
```bash
#!/bin/bash
while :
do
   sh launcher.sh
   sleep 30
done
```

Windows:
```batch
:loop
   launcher.bat
   TIMEOUT 30
goto loop
```
Than you can just do `/stop` to restart.
(yes I was bored :worried: )

**Comment by EverNife** [comment]
I recommend mark2 ! :D

**Comment by DarkBlade177** [comment]
Ty thomas, to turn off the server how to kill it?
I am on linux (ubuntu) (Sorry i am newbie T,T)

**Comment by thomas15v** [comment]
@DarkBlade177 During the timeout do `ctrl + c`.
